# Generated by Django 5.2.13 on 2026-04-25 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='背景颜色'),
        ),
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='背景图片URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_color',
            field=models.CharField(default='#1890ff', max_length=20, verbose_name='图标颜色'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_emoji',
            field=models.CharField(default='📁', max_length=10, verbose_name='Emoji图标'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='图标图片URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_type',
            field=models.CharField(choices=[('emoji', 'Emoji'), ('color', '颜色'), ('image', '图片')], default='emoji', max_length=20, verbose_name='图标类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', '进行中'), ('archived', '已归档'), ('draft', '草稿')], default='active', max_length=20, verbose_name='项目状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('private', '私有')], default='private', max_length=20, verbose_name='可见性'),
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('type', models.CharField(choices=[('header', '全局Headers'), ('auth', '认证配置'), ('variable', '环境变量')], max_length=20, verbose_name='配置类型')),
                ('auth_type', models.CharField(choices=[('none', '无认证'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('apikey', 'API Key'), ('oauth2', 'OAuth 2.0')], default='none', max_length=20, verbose_name='认证类型')),
                ('config_data', models.JSONField(default=dict, verbose_name='配置数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_global', models.BooleanField(default=False, verbose_name='是否全局生效')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_configs', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '全局配置',
                'verbose_name_plural': '全局配置',
                'ordering': ['type', '-is_global', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('type', models.CharField(choices=[('development', '开发环境'), ('testing', '测试环境'), ('staging', '预发布环境'), ('production', '生产环境'), ('custom', '自定义')], default='development', max_length=20, verbose_name='环境类型')),
                ('host', models.CharField(max_length=500, verbose_name='Host地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认环境')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '环境配置',
                'verbose_name_plural': '环境配置',
                'ordering': ['-is_default', 'created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
