# Generated by Django 5.2.13 on 2026-04-25 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mock配置名称')),
                ('status_code', models.IntegerField(default=200, verbose_name='响应状态码')),
                ('response_headers', models.JSONField(blank=True, default=dict, verbose_name='响应头')),
                ('response_body', models.JSONField(blank=True, default=dict, null=True, verbose_name='响应体')),
                ('response_body_raw', models.TextField(blank=True, null=True, verbose_name='原始响应体')),
                ('delay_ms', models.IntegerField(default=0, verbose_name='延迟时间(ms)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_configs', to='apis.apidefinition', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': 'Mock配置',
                'verbose_name_plural': 'Mock配置',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=20, verbose_name='请求方法')),
                ('request_path', models.CharField(max_length=1000, verbose_name='请求路径')),
                ('request_headers', models.JSONField(default=dict, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('request_query_params', models.JSONField(default=dict, verbose_name='查询参数')),
                ('response_status', models.IntegerField(verbose_name='响应状态码')),
                ('response_headers', models.JSONField(default=dict, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='响应体')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='调用时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_logs', to='apis.apidefinition', verbose_name='所属接口')),
                ('mock_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='mock_server.mockconfig', verbose_name='Mock配置')),
            ],
            options={
                'verbose_name': 'Mock调用日志',
                'verbose_name_plural': 'Mock调用日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
