# Generated by Django 5.2.13 on 2026-04-25 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='测试用例名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用例描述')),
                ('request_params', models.JSONField(blank=True, default=list, verbose_name='请求参数')),
                ('request_headers', models.JSONField(blank=True, default=list, verbose_name='请求头')),
                ('request_body', models.JSONField(blank=True, default=dict, null=True, verbose_name='请求体')),
                ('expected_status_code', models.IntegerField(default=200, verbose_name='期望状态码')),
                ('expected_response', models.JSONField(blank=True, default=dict, null=True, verbose_name='期望响应')),
                ('expected_response_schema', models.JSONField(blank=True, default=dict, null=True, verbose_name='期望响应Schema')),
                ('assertions', models.JSONField(blank=True, default=list, verbose_name='断言规则')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='apis.apidefinition', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='测试运行名称')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='运行状态')),
                ('total_tests', models.IntegerField(default=0, verbose_name='总测试数')),
                ('passed_tests', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed_tests', models.IntegerField(default=0, verbose_name='失败数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_ms', models.FloatField(default=0, verbose_name='运行时长(ms)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试运行',
                'verbose_name_plural': '测试运行',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='测试名称')),
                ('is_passed', models.BooleanField(verbose_name='是否通过')),
                ('request_url', models.CharField(max_length=1000, verbose_name='请求URL')),
                ('request_method', models.CharField(max_length=20, verbose_name='请求方法')),
                ('request_headers', models.JSONField(default=dict, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('response_status', models.IntegerField(verbose_name='响应状态码')),
                ('response_headers', models.JSONField(default=dict, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='响应体')),
                ('response_time', models.FloatField(verbose_name='响应时间(ms)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('assertion_results', models.JSONField(blank=True, default=list, verbose_name='断言结果')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='执行时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='apis.apidefinition', verbose_name='所属接口')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='test_runner.testcase', verbose_name='测试用例')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='test_runner.testrun', verbose_name='测试运行')),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='测试套件名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='套件描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('apis', models.ManyToManyField(blank=True, related_name='test_suites', to='apis.apidefinition', verbose_name='包含接口')),
                ('groups', models.ManyToManyField(blank=True, related_name='test_suites', to='projects.apigroup', verbose_name='包含分组')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testrun',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='test_runner.testsuite', verbose_name='测试套件'),
        ),
    ]
