# Generated by Django 5.2.13 on 2026-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitesthistory',
            name='environment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='使用的环境ID'),
        ),
        migrations.AddField(
            model_name='apitesthistory',
            name='used_environment_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='使用的环境名称'),
        ),
    ]
